fix/git-start

diff --git a/.scripts/git-start b/.scripts/git-start
--- a/.scripts/git-start
+++ b/.scripts/git-start
@@ -1,39 +1,28 @@
 #!/bin/zsh -e
 
-NEW_BRANCH=$1;
+if [[ -n $1 ]]; then
+  # 引数あり：新しいブランチを作成
+  NEW_BRANCH=$1
+  echo "⚒️ Creating new branch: [$NEW_BRANCH]"
 
-if [[ -z $1  ]]; then
-  echo ' Use this branch as feature branch.';
-  BASE_BRANCH=$(git show-branch | grep '!' | awk -F'[]~^[]' '{print $2}');
-  NEW_BRANCH=$(git rev-parse --abbrev-ref @);
+  if ! git branch | grep -q "^[* ] ${NEW_BRANCH}$"; then
+    git checkout -b "$NEW_BRANCH"
+    git commit --allow-empty -m "$NEW_BRANCH"
+  fi
 else
-  BASE_BRANCH=$(git rev-parse --abbrev-ref @);
-fi;
+  # 引数なし：現在のブランチを使う
+  NEW_BRANCH=$(git rev-parse --abbrev-ref @)
+  echo "👀 Using current branch: [$NEW_BRANCH]"
+fi
 
-if [[ $BASE_BRANCH = "main" ]] || [[ $BASE_BRANCH = "master" ]]; then
-  echo "  🔥ATTENTION!! you are trying to make branch from [$BASE_BRANCH]🔥";
-fi;
+# リモートにプッシュ
+git branch -r | grep -q "origin/${NEW_BRANCH}$" || git push -u origin "$NEW_BRANCH"
+echo '✅ Success! Created remote branch'
 
-read "yn?  You want to make Base Branch: [$BASE_BRANCH] -> New Branch: [$NEW_BRANCH]? (y/n)  ";
-
-case $yn in
-  [yY]* ) echo "  🆗 Let's Start!";;
-  * ) exit 1;;
-esac;
-
-if ! git branch | grep -q "^[* ] ${NEW_BRANCH}$"; then
-  git checkout -b "$NEW_BRANCH";
-  git commit --allow-empty -m "$NEW_BRANCH";
-  # echo "make new branch:$NEW_BRANCH"
-fi;
-
-git branch -r | grep -q "origin/${NEW_BRANCH}$" || git push -u origin "$NEW_BRANCH";
-# git branch -r | grep "origin/${NEW_BRANCH}$" || echo "push branch";
-echo '✅ Success! Created remote branch';
-
+# PRを作成
 if ! gh pr create -d; then
-  echo '❌ Failed to create draft PR';
-  exit 1;
-fi;
+  echo '❌ Failed to create draft PR'
+  exit 1
+fi
 
-echo '✅ Success! Created draft PR';
+echo '✅ Success! Created draft PR'
